# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t ci set-pipeline -p maven-cf-simple -c pipeline.yml -l pipeline-secrets.yml
---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/vipinvkmenon/EmbeddedRedisServerDocker.git
    branch: master
    skip_cert_check: true
    skip_ssl_verification: true


jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/build.yml